In [28]:
import numpy as np
import tvm
from tvm.script import tir as T

In [29]:
@tvm.script.ir_module
class MyModuleVecAdd:
    @T.prim_func
    def main(
        A: T.Buffer((1024,), "float32"),
        B: T.Buffer((1024,), "float32"),
        C: T.Buffer((1024,), "float32"),
    ) -> None:
        T.func_attr({"global_symbol": "main", "tirx.noalias": True})
        for i in T.grid(1024):
            with T.sblock("C"):
                vi = T.axis.remap("S", [i])
                C[vi] = A[vi] + B[vi]

In [30]:
sch = tvm.s_tir.Schedule(MyModuleVecAdd)
block_C = sch.get_sblock("C")
(i,) = sch.get_loops(block=block_C)
i0, i1 = sch.split(i, [None, 128])
sch.mod.show()

In [31]:
sch.bind(i0, "blockIdx.x")
sch.bind(i1, "threadIdx.x")
sch.mod.show()

In [32]:
rt_mod = tvm.compile(sch.mod, target="cuda")

A_np = np.random.uniform(size=(1024,)).astype("float32")
B_np = np.random.uniform(size=(1024,)).astype("float32")
A_nd = tvm.runtime.tensor(A_np, device=tvm.cuda(0))
B_nd = tvm.runtime.tensor(B_np, device=tvm.cuda(0))
C_nd = tvm.runtime.tensor(np.zeros((1024,), dtype="float32"), device=tvm.cuda(0))

rt_mod["main"](A_nd, B_nd, C_nd)
print(A_nd)
print(B_nd)
print(C_nd)

[0.46092746 0.2972198  0.6475623  ... 0.4914641  0.82321    0.96041805]
[0.8281219  0.18705241 0.4382954  ... 0.41424918 0.63458484 0.43275172]
[1.2890494  0.48427224 1.0858577  ... 0.9057133  1.4577949  1.3931698 ]

In [33]:
@tvm.script.ir_module
class MyModuleWindowSum:
    @T.prim_func
    def main(A: T.Buffer((1027,), "float32"), B: T.Buffer((1024,), "float32")) -> None:
        T.func_attr({"global_symbol": "main", "tirx.noalias": True})
        for i in T.grid(1024):
            with T.sblock("C"):
                vi = T.axis.remap("S", [i])
                B[vi] = A[vi] + A[vi + 1] + A[vi + 2]

In [34]:
sch = tvm.s_tir.Schedule(MyModuleWindowSum)
nthread = 128
block_C = sch.get_sblock("C")
(i,) = sch.get_loops(block=block_C)
i0, i1 = sch.split(i, [None, nthread])
sch.bind(i0, "blockIdx.x")
sch.bind(i1, "threadIdx.x")
sch.mod.show()

In [35]:
A_shared = sch.cache_read(block_C, read_buffer_index=0, storage_scope="shared")
sch.compute_at(A_shared, i1)
sch.mod.show()

In [36]:
ax = sch.get_loops(A_shared)[-1]
ax0, ax1 = sch.split(ax, [None, nthread])
sch.bind(ax1, "threadIdx.x")
sch.mod.show()

In [37]:
rt_mod = tvm.compile(sch.mod, target="cuda")
print(rt_mod.mod.inspect_source())

; ModuleID = 'TVMMod'
source_filename = "TVMMod"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-redhat-linux-gnu"

%0 = type { i32, i32, double }

@__tvm_ffi__library_ctx = linkonce dllexport local_unnamed_addr global ptr null, align 8
@__TVMFFIFunctionCall = linkonce dllexport local_unnamed_addr global ptr null, align 8
@__TVMBackendGetFuncFromEnv = linkonce dllexport local_unnamed_addr global ptr null, align 8
@.str = private constant [10 x i8] c"TypeError\00", align 1
@.str.1 = private constant [10 x i8] c"Expected \00", align 1
@.str.2 = private constant [2 x i8] c"2\00", align 1
@.str.3 = private constant [11 x i8] c" arguments\00", align 1
@.str.4 = private constant [19 x i8] c" when calling:\0A  `\00", align 1
@.str.5 = private constant [61 x i8] c"main(A: Tensor([1027], float32), B: Tensor([1024], float32))\00", align 1
@.str.6 = private constant [2 x i8] c"`\00", align 1
@.str.7 = private constant [21 x i8] c"args pointer is NULL\00", align 1
@.str.8 = private constant [30 x i8] c"Mismatched type on argument #\00", align 1
@.str.9 = private constant [2 x i8] c"0\00", align 1
@.str.10 = private constant [15 x i8] c"`,\0A  expected \00", align 1
@.str.11 = private constant [7 x i8] c"Tensor\00", align 1
@.str.12 = private constant [2 x i8] c"1\00", align 1
@.str.13 = private constant [11 x i8] c"ValueError\00", align 1
@.str.14 = private constant [12 x i8] c"Mismatched \00", align 1
@.str.15 = private constant [2 x i8] c"A\00", align 1
@.str.16 = private constant [20 x i8] c".ndim on argument #\00", align 1
@.str.17 = private constant [21 x i8] c".dtype on argument #\00", align 1
@.str.18 = private constant [8 x i8] c"float32\00", align 1
@.str.19 = private constant [27 x i8] c".device_type on argument #\00", align 1
@.str.20 = private constant [5 x i8] c"cuda\00", align 1
@.str.21 = private constant [2 x i8] c"B\00", align 1
@.str.22 = private constant [23 x i8] c".strides on argument #\00", align 1
@.str.23 = private constant [34 x i8] c"`,\0A  expected to be compact array\00", align 1
@.str.24 = private constant [36 x i8] c" data pointer is NULL on argument #\00", align 1
@.str.25 = private constant [36 x i8] c"`,\0A  expected non-NULL data pointer\00", align 1
@.str.26 = private constant [12 x i8] c"B.device_id\00", align 1
@.str.27 = private constant [15 x i8] c" on argument #\00", align 1
@.str.28 = private constant [24 x i8] c"`,\0A  expected to match \00", align 1
@.str.29 = private constant [12 x i8] c"A.device_id\00", align 1
@.str.30 = private constant [9 x i8] c"Invalid \00", align 1
@.str.31 = private constant [11 x i8] c"A.shape[0]\00", align 1
@.str.32 = private constant [5 x i8] c"1027\00", align 1
@.str.33 = private constant [14 x i8] c"A.byte_offset\00", align 1
@.str.34 = private constant [11 x i8] c"B.shape[0]\00", align 1
@.str.35 = private constant [5 x i8] c"1024\00", align 1
@.str.36 = private constant [14 x i8] c"B.byte_offset\00", align 1
@.tvm_func.__tvm_set_device = internal unnamed_addr global ptr null, align 8
@.str.37 = private constant [17 x i8] c"__tvm_set_device\00", align 1
@.tvm_func.main_kernel = internal unnamed_addr global ptr null, align 8
@.str.38 = private constant [12 x i8] c"main_kernel\00", align 1
@llvm.global_ctors = appending global [0 x { i32, ptr, ptr }] zeroinitializer

define dllexport i32 @__tvm_ffi_main(ptr nocapture readnone %self_handle, ptr readonly %args, i32 %num_args, ptr nocapture readnone %result) local_unnamed_addr #0 !dbg !5 {
entry:
  %0 = alloca ptr, align 8, !dbg !15
    #dbg_value(ptr %self_handle, !11, !DIExpression(), !26)
    #dbg_value(ptr %args, !12, !DIExpression(), !26)
    #dbg_value(i32 %num_args, !13, !DIExpression(), !26)
    #dbg_value(ptr %result, !14, !DIExpression(), !26)
  %1 = alloca ptr, align 8, !dbg !26
  %stack_ffi_any50 = alloca [5 x %0], align 8, !dbg !26
    #dbg_declare(ptr %stack_ffi_any50, !27, !DIExpression(), !26)
    #dbg_declare(ptr %stack_ffi_any50, !27, !DIExpression(), !26)
  %2 = icmp eq i32 %num_args, 2, !dbg !26
  br i1 %2, label %assert_end, label %assert_fail, !dbg !26, !prof !28

common.ret:                                       ; preds = %main_compute_.exit, %handle_init_end, %handle_init, %assert_fail41, %assert_fail39, %assert_fail37, %assert_fail35, %assert_fail33, %assert_fail31, %assert_fail29, %assert_fail25, %assert_fail23, %assert_fail21, %assert_fail19, %assert_fail17, %assert_fail15, %assert_fail13, %assert_fail11, %assert_fail9, %assert_fail7, %assert_fail5, %assert_fail3, %assert_fail1, %assert_fail
  %common.ret.op = phi i32 [ -1, %assert_fail ], [ -1, %assert_fail1 ], [ -1, %assert_fail3 ], [ -1, %assert_fail5 ], [ -1, %assert_fail7 ], [ -1, %assert_fail9 ], [ -1, %assert_fail11 ], [ -1, %assert_fail13 ], [ -1, %assert_fail15 ], [ -1, %assert_fail17 ], [ -1, %assert_fail19 ], [ -1, %assert_fail21 ], [ -1, %assert_fail23 ], [ -1, %assert_fail25 ], [ -1, %assert_fail29 ], [ -1, %assert_fail31 ], [ -1, %assert_fail33 ], [ -1, %assert_fail35 ], [ -1, %assert_fail37 ], [ -1, %assert_fail39 ], [ -1, %assert_fail41 ], [ %85, %handle_init ], [ %88, %handle_init_end ], [ %common.ret.op.i, %main_compute_.exit ]
  ret i32 %common.ret.op, !dbg !26

assert_fail:                                      ; preds = %entry
  tail call fastcc void @__tvm_set_raised_6(ptr nonnull @.str, i32 6, ptr nonnull @.str.1, ptr nonnull @.str.2, ptr nonnull @.str.3, ptr nonnull @.str.4, ptr nonnull @.str.5, ptr nonnull @.str.6), !dbg !26
  br label %common.ret, !dbg !26

assert_end:                                       ; preds = %entry
  %.not = icmp eq ptr %args, null, !dbg !26
  br i1 %.not, label %assert_fail1, label %assert_end2, !dbg !26, !prof !29

assert_fail1:                                     ; preds = %assert_end
  tail call fastcc void @__tvm_set_raised_6(ptr nonnull @.str, i32 4, ptr nonnull @.str.7, ptr nonnull @.str.4, ptr nonnull @.str.5, ptr nonnull @.str.6, ptr null, ptr null), !dbg !26
  br label %common.ret, !dbg !26

assert_end2:                                      ; preds = %assert_end
  %A_handle.type_index = load i32, ptr %args, align 4, !dbg !26
    #dbg_value(i32 %A_handle.type_index, !30, !DIExpression(), !26)
    #dbg_value(i32 %A_handle.type_index, !30, !DIExpression(), !26)
  %A_handle.type_index.fr = freeze i32 %A_handle.type_index, !dbg !26
  %3 = icmp sgt i32 %A_handle.type_index.fr, 63, !dbg !26
  br i1 %3, label %assert_end4, label %switch.early.test, !dbg !26

switch.early.test:                                ; preds = %assert_end2
  switch i32 %A_handle.type_index.fr, label %assert_fail3 [
    i32 7, label %assert_end4
    i32 4, label %assert_end4
    i32 0, label %assert_end4
  ], !dbg !26

assert_fail3:                                     ; preds = %switch.early.test
  tail call fastcc void @__tvm_set_raised_6(ptr nonnull @.str, i32 6, ptr nonnull @.str.8, ptr nonnull @.str.9, ptr nonnull @.str.4, ptr nonnull @.str.5, ptr nonnull @.str.10, ptr nonnull @.str.11), !dbg !26
  br label %common.ret, !dbg !26

assert_end4:                                      ; preds = %switch.early.test, %switch.early.test, %switch.early.test, %assert_end2
  %4 = getelementptr inbounds i8, ptr %args, i64 8, !dbg !26
  %5 = load ptr, ptr %4, align 8, !dbg !26
  %6 = icmp eq i32 %A_handle.type_index.fr, 70, !dbg !26
  %A_handle.idx = select i1 %6, i64 24, i64 0, !dbg !26
  %A_handle = getelementptr inbounds i8, ptr %5, i64 %A_handle.idx, !dbg !26
    #dbg_declare(ptr %A_handle, !31, !DIExpression(), !26)
    #dbg_declare(ptr %A_handle, !31, !DIExpression(), !26)
  %7 = getelementptr inbounds i8, ptr %args, i64 16, !dbg !26
  %B_handle.type_index = load i32, ptr %7, align 4, !dbg !26
    #dbg_value(i32 %B_handle.type_index, !32, !DIExpression(), !26)
    #dbg_value(i32 %B_handle.type_index, !32, !DIExpression(), !26)
  %B_handle.type_index.fr = freeze i32 %B_handle.type_index, !dbg !26
  %8 = icmp sgt i32 %B_handle.type_index.fr, 63, !dbg !26
  br i1 %8, label %assert_end6, label %switch.early.test47, !dbg !26

switch.early.test47:                              ; preds = %assert_end4
  switch i32 %B_handle.type_index.fr, label %assert_fail5 [
    i32 7, label %assert_end6
    i32 4, label %assert_end6
    i32 0, label %assert_end6
  ], !dbg !26

assert_fail5:                                     ; preds = %switch.early.test47
  tail call fastcc void @__tvm_set_raised_6(ptr nonnull @.str, i32 6, ptr nonnull @.str.8, ptr nonnull @.str.12, ptr nonnull @.str.4, ptr nonnull @.str.5, ptr nonnull @.str.10, ptr nonnull @.str.11), !dbg !26
  br label %common.ret, !dbg !26

assert_end6:                                      ; preds = %switch.early.test47, %switch.early.test47, %switch.early.test47, %assert_end4
  %9 = getelementptr inbounds i8, ptr %args, i64 24, !dbg !26
  %10 = load ptr, ptr %9, align 8, !dbg !26
  %11 = icmp eq i32 %B_handle.type_index.fr, 70, !dbg !26
  %B_handle.idx = select i1 %11, i64 24, i64 0, !dbg !26
  %B_handle = getelementptr inbounds i8, ptr %10, i64 %B_handle.idx, !dbg !26
    #dbg_declare(ptr %B_handle, !33, !DIExpression(), !26)
    #dbg_declare(ptr %B_handle, !33, !DIExpression(), !26)
  %.not51 = icmp eq ptr %5, null, !dbg !26
  br i1 %.not51, label %assert_fail7, label %assert_end8, !dbg !26, !prof !29

assert_fail7:                                     ; preds = %assert_end6
  tail call fastcc void @__tvm_set_raised_6(ptr nonnull @.str, i32 6, ptr nonnull @.str.8, ptr nonnull @.str.9, ptr nonnull @.str.4, ptr nonnull @.str.5, ptr nonnull @.str.10, ptr nonnull @.str.11), !dbg !26
  br label %common.ret, !dbg !26

assert_end8:                                      ; preds = %assert_end6
  %12 = getelementptr inbounds i8, ptr %A_handle, i64 16, !dbg !26
  %13 = load i32, ptr %12, align 4, !dbg !26
  %14 = icmp eq i32 %13, 1, !dbg !26
  br i1 %14, label %assert_end10, label %assert_fail9, !dbg !26, !prof !28

assert_fail9:                                     ; preds = %assert_end8
  tail call fastcc void @__tvm_set_raised_12(ptr nonnull @.str.13, i32 8, ptr nonnull @.str.14, ptr nonnull @.str.15, ptr nonnull @.str.16, ptr nonnull @.str.9, ptr nonnull @.str.10, ptr nonnull @.str.12), !dbg !26
  br label %common.ret, !dbg !26

assert_end10:                                     ; preds = %assert_end8
  %15 = getelementptr inbounds i8, ptr %A_handle, i64 22, !dbg !26
  %16 = load i16, ptr %15, align 2, !dbg !26
  %17 = icmp eq i16 %16, 1, !dbg !26
  %18 = getelementptr inbounds i8, ptr %A_handle, i64 21, !dbg !26
  %19 = load i8, ptr %18, align 1, !dbg !26
  %20 = icmp eq i8 %19, 32, !dbg !26
  %21 = getelementptr inbounds i8, ptr %A_handle, i64 20, !dbg !26
  %22 = load i8, ptr %21, align 1, !dbg !26
  %23 = icmp eq i8 %22, 2, !dbg !26
  %24 = and i1 %20, %23, !dbg !26
  %25 = and i1 %17, %24, !dbg !26
  br i1 %25, label %assert_end12, label %assert_fail11, !dbg !26, !prof !28

assert_fail11:                                    ; preds = %assert_end10
  tail call fastcc void @__tvm_set_raised_12(ptr nonnull @.str, i32 8, ptr nonnull @.str.14, ptr nonnull @.str.15, ptr nonnull @.str.17, ptr nonnull @.str.9, ptr nonnull @.str.10, ptr nonnull @.str.18), !dbg !26
  br label %common.ret, !dbg !26

assert_end12:                                     ; preds = %assert_end10
  %26 = getelementptr inbounds i8, ptr %A_handle, i64 24, !dbg !26
  %main.A_handle_shape = load ptr, ptr %26, align 8, !dbg !26
    #dbg_declare(ptr %main.A_handle_shape, !34, !DIExpression(), !26)
    #dbg_declare(ptr %main.A_handle_shape, !34, !DIExpression(), !26)
  %27 = getelementptr inbounds i8, ptr %A_handle, i64 32, !dbg !26
  %main.A_handle_strides = load ptr, ptr %27, align 8, !dbg !26
    #dbg_declare(ptr %main.A_handle_strides, !35, !DIExpression(), !26)
    #dbg_declare(ptr %main.A_handle_strides, !35, !DIExpression(), !26)
  %28 = getelementptr inbounds i8, ptr %A_handle, i64 8, !dbg !26
  %29 = load i32, ptr %28, align 4, !dbg !26
  %30 = icmp eq i32 %29, 2, !dbg !26
  br i1 %30, label %assert_end14, label %assert_fail13, !dbg !26, !prof !28

assert_fail13:                                    ; preds = %assert_end12
  tail call fastcc void @__tvm_set_raised_12(ptr nonnull @.str.13, i32 8, ptr nonnull @.str.14, ptr nonnull @.str.15, ptr nonnull @.str.19, ptr nonnull @.str.9, ptr nonnull @.str.10, ptr nonnull @.str.20), !dbg !26
  br label %common.ret, !dbg !26

assert_end14:                                     ; preds = %assert_end12
  %31 = getelementptr inbounds i8, ptr %A_handle, i64 12, !dbg !26
  %dev_id = load i32, ptr %31, align 4, !dbg !26
    #dbg_value(i32 %dev_id, !36, !DIExpression(), !26)
    #dbg_value(i32 %dev_id, !36, !DIExpression(), !26)
  %A = load ptr, ptr %A_handle, align 8, !dbg !26
    #dbg_declare(ptr %A, !37, !DIExpression(), !26)
    #dbg_declare(ptr %A, !37, !DIExpression(), !26)
  call void @llvm.assume(i1 true) [ "align"(ptr %A, i64 64) ], !dbg !26
  %.not52 = icmp eq ptr %10, null, !dbg !26
  br i1 %.not52, label %assert_fail15, label %assert_end16, !dbg !26, !prof !29

assert_fail15:                                    ; preds = %assert_end14
  tail call fastcc void @__tvm_set_raised_6(ptr nonnull @.str, i32 6, ptr nonnull @.str.8, ptr nonnull @.str.12, ptr nonnull @.str.4, ptr nonnull @.str.5, ptr nonnull @.str.10, ptr nonnull @.str.11), !dbg !26
  br label %common.ret, !dbg !26

assert_end16:                                     ; preds = %assert_end14
  %32 = getelementptr inbounds i8, ptr %B_handle, i64 16, !dbg !26
  %33 = load i32, ptr %32, align 4, !dbg !26
  %34 = icmp eq i32 %33, 1, !dbg !26
  br i1 %34, label %assert_end18, label %assert_fail17, !dbg !26, !prof !28

assert_fail17:                                    ; preds = %assert_end16
  tail call fastcc void @__tvm_set_raised_12(ptr nonnull @.str.13, i32 8, ptr nonnull @.str.14, ptr nonnull @.str.21, ptr nonnull @.str.16, ptr nonnull @.str.12, ptr nonnull @.str.10, ptr nonnull @.str.12), !dbg !26
  br label %common.ret, !dbg !26

assert_end18:                                     ; preds = %assert_end16
  %35 = getelementptr inbounds i8, ptr %B_handle, i64 22, !dbg !26
  %36 = load i16, ptr %35, align 2, !dbg !26
  %37 = icmp eq i16 %36, 1, !dbg !26
  %38 = getelementptr inbounds i8, ptr %B_handle, i64 21, !dbg !26
  %39 = load i8, ptr %38, align 1, !dbg !26
  %40 = icmp eq i8 %39, 32, !dbg !26
  %41 = getelementptr inbounds i8, ptr %B_handle, i64 20, !dbg !26
  %42 = load i8, ptr %41, align 1, !dbg !26
  %43 = icmp eq i8 %42, 2, !dbg !26
  %44 = and i1 %40, %43, !dbg !26
  %45 = and i1 %37, %44, !dbg !26
  br i1 %45, label %assert_end20, label %assert_fail19, !dbg !26, !prof !28

assert_fail19:                                    ; preds = %assert_end18
  tail call fastcc void @__tvm_set_raised_12(ptr nonnull @.str, i32 8, ptr nonnull @.str.14, ptr nonnull @.str.21, ptr nonnull @.str.17, ptr nonnull @.str.12, ptr nonnull @.str.10, ptr nonnull @.str.18), !dbg !26
  br label %common.ret, !dbg !26

assert_end20:                                     ; preds = %assert_end18
  %46 = getelementptr inbounds i8, ptr %B_handle, i64 24, !dbg !26
  %main.B_handle_shape = load ptr, ptr %46, align 8, !dbg !26
    #dbg_declare(ptr %main.B_handle_shape, !38, !DIExpression(), !26)
    #dbg_declare(ptr %main.B_handle_shape, !38, !DIExpression(), !26)
  %47 = getelementptr inbounds i8, ptr %B_handle, i64 32, !dbg !26
  %main.B_handle_strides = load ptr, ptr %47, align 8, !dbg !26
    #dbg_declare(ptr %main.B_handle_strides, !39, !DIExpression(), !26)
    #dbg_declare(ptr %main.B_handle_strides, !39, !DIExpression(), !26)
  %48 = getelementptr inbounds i8, ptr %B_handle, i64 8, !dbg !26
  %49 = load i32, ptr %48, align 4, !dbg !26
  %50 = icmp eq i32 %49, 2, !dbg !26
  br i1 %50, label %assert_end22, label %assert_fail21, !dbg !26, !prof !28

assert_fail21:                                    ; preds = %assert_end20
  tail call fastcc void @__tvm_set_raised_12(ptr nonnull @.str.13, i32 8, ptr nonnull @.str.14, ptr nonnull @.str.21, ptr nonnull @.str.19, ptr nonnull @.str.12, ptr nonnull @.str.10, ptr nonnull @.str.20), !dbg !26
  br label %common.ret, !dbg !26

assert_end22:                                     ; preds = %assert_end20
  %B = load ptr, ptr %B_handle, align 8, !dbg !26
    #dbg_declare(ptr %B, !40, !DIExpression(), !26)
    #dbg_declare(ptr %B, !40, !DIExpression(), !26)
  call void @llvm.assume(i1 true) [ "align"(ptr %B, i64 64) ], !dbg !26
  %.not53 = icmp eq ptr %main.A_handle_strides, null, !dbg !26
  br i1 %.not53, label %if_end, label %if_then, !dbg !26, !prof !29

if_then:                                          ; preds = %assert_end22
  %51 = load i64, ptr %main.A_handle_strides, align 8, !dbg !26
  %52 = and i64 %51, 4294967295, !dbg !26
  %53 = icmp eq i64 %52, 1, !dbg !26
  br i1 %53, label %if_end, label %assert_fail23, !dbg !26, !prof !28

if_end:                                           ; preds = %if_then, %assert_end22
  %.not54 = icmp eq ptr %A, null, !dbg !26
  br i1 %.not54, label %assert_fail25, label %assert_end26, !dbg !26, !prof !29

assert_fail23:                                    ; preds = %if_then
  tail call fastcc void @__tvm_set_raised_12(ptr nonnull @.str.13, i32 7, ptr nonnull @.str.14, ptr nonnull @.str.15, ptr nonnull @.str.22, ptr nonnull @.str.9, ptr nonnull @.str.23, ptr null), !dbg !26
  br label %common.ret, !dbg !26

assert_fail25:                                    ; preds = %if_end
  tail call fastcc void @__tvm_set_raised_6(ptr nonnull @.str.13, i32 6, ptr nonnull @.str.15, ptr nonnull @.str.24, ptr nonnull @.str.9, ptr nonnull @.str.4, ptr nonnull @.str.5, ptr nonnull @.str.25), !dbg !26
  br label %common.ret, !dbg !26

assert_end26:                                     ; preds = %if_end
  %.not55 = icmp eq ptr %main.B_handle_strides, null, !dbg !26
  br i1 %.not55, label %if_end28, label %if_then27, !dbg !26, !prof !29

if_then27:                                        ; preds = %assert_end26
  %54 = load i64, ptr %main.B_handle_strides, align 8, !dbg !26
  %55 = and i64 %54, 4294967295, !dbg !26
  %56 = icmp eq i64 %55, 1, !dbg !26
  br i1 %56, label %if_end28, label %assert_fail29, !dbg !26, !prof !28

if_end28:                                         ; preds = %if_then27, %assert_end26
  %57 = getelementptr inbounds i8, ptr %B_handle, i64 12, !dbg !26
  %58 = load i32, ptr %57, align 4, !dbg !26
  %59 = icmp eq i32 %dev_id, %58, !dbg !26
  br i1 %59, label %assert_end32, label %assert_fail31, !dbg !26, !prof !28

assert_fail29:                                    ; preds = %if_then27
  tail call fastcc void @__tvm_set_raised_12(ptr nonnull @.str.13, i32 7, ptr nonnull @.str.14, ptr nonnull @.str.21, ptr nonnull @.str.22, ptr nonnull @.str.12, ptr nonnull @.str.23, ptr null), !dbg !26
  br label %common.ret, !dbg !26

assert_fail31:                                    ; preds = %if_end28
  tail call fastcc void @__tvm_set_raised_12(ptr nonnull @.str.13, i32 8, ptr nonnull @.str.14, ptr nonnull @.str.26, ptr nonnull @.str.27, ptr nonnull @.str.12, ptr nonnull @.str.28, ptr nonnull @.str.29), !dbg !26
  br label %common.ret, !dbg !26

assert_end32:                                     ; preds = %if_end28
  %.not56 = icmp eq ptr %B, null, !dbg !26
  br i1 %.not56, label %assert_fail33, label %assert_end34, !dbg !26, !prof !29

assert_fail33:                                    ; preds = %assert_end32
  tail call fastcc void @__tvm_set_raised_6(ptr nonnull @.str.13, i32 6, ptr nonnull @.str.21, ptr nonnull @.str.24, ptr nonnull @.str.12, ptr nonnull @.str.4, ptr nonnull @.str.5, ptr nonnull @.str.25), !dbg !26
  br label %common.ret, !dbg !26

assert_end34:                                     ; preds = %assert_end32
  %60 = load i64, ptr %main.A_handle_shape, align 8, !dbg !26
  %61 = and i64 %60, 4294967295, !dbg !26
  %62 = icmp eq i64 %61, 1027, !dbg !26
  br i1 %62, label %assert_end36, label %assert_fail35, !dbg !26, !prof !28

assert_fail35:                                    ; preds = %assert_end34

In [38]:
rt_mod = tvm.compile(sch.mod, target="metal")
print(rt_mod.mod.inspect_source())

; ModuleID = 'TVMMod'
source_filename = "TVMMod"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-redhat-linux-gnu"

%0 = type { i32, i32, double }

@__tvm_ffi__library_ctx = linkonce dllexport local_unnamed_addr global ptr null, align 8
@__TVMFFIFunctionCall = linkonce dllexport local_unnamed_addr global ptr null, align 8
@__TVMBackendGetFuncFromEnv = linkonce dllexport local_unnamed_addr global ptr null, align 8
@.str = private constant [10 x i8] c"TypeError\00", align 1
@.str.1 = private constant [10 x i8] c"Expected \00", align 1
@.str.2 = private constant [2 x i8] c"2\00", align 1
@.str.3 = private constant [11 x i8] c" arguments\00", align 1
@.str.4 = private constant [19 x i8] c" when calling:\0A  `\00", align 1
@.str.5 = private constant [61 x i8] c"main(A: Tensor([1027], float32), B: Tensor([1024], float32))\00", align 1
@.str.6 = private constant [2 x i8] c"`\00", align 1
@.str.7 = private constant [21 x i8] c"args pointer is NULL\00", align 1
@.str.8 = private constant [30 x i8] c"Mismatched type on argument #\00", align 1
@.str.9 = private constant [2 x i8] c"0\00", align 1
@.str.10 = private constant [15 x i8] c"`,\0A  expected \00", align 1
@.str.11 = private constant [7 x i8] c"Tensor\00", align 1
@.str.12 = private constant [2 x i8] c"1\00", align 1
@.str.13 = private constant [11 x i8] c"ValueError\00", align 1
@.str.14 = private constant [12 x i8] c"Mismatched \00", align 1
@.str.15 = private constant [2 x i8] c"A\00", align 1
@.str.16 = private constant [20 x i8] c".ndim on argument #\00", align 1
@.str.17 = private constant [21 x i8] c".dtype on argument #\00", align 1
@.str.18 = private constant [8 x i8] c"float32\00", align 1
@.str.19 = private constant [27 x i8] c".device_type on argument #\00", align 1
@.str.20 = private constant [6 x i8] c"metal\00", align 1
@.str.21 = private constant [2 x i8] c"B\00", align 1
@.str.22 = private constant [23 x i8] c".strides on argument #\00", align 1
@.str.23 = private constant [34 x i8] c"`,\0A  expected to be compact array\00", align 1
@.str.24 = private constant [36 x i8] c" data pointer is NULL on argument #\00", align 1
@.str.25 = private constant [36 x i8] c"`,\0A  expected non-NULL data pointer\00", align 1
@.str.26 = private constant [12 x i8] c"B.device_id\00", align 1
@.str.27 = private constant [15 x i8] c" on argument #\00", align 1
@.str.28 = private constant [24 x i8] c"`,\0A  expected to match \00", align 1
@.str.29 = private constant [12 x i8] c"A.device_id\00", align 1
@.str.30 = private constant [9 x i8] c"Invalid \00", align 1
@.str.31 = private constant [11 x i8] c"A.shape[0]\00", align 1
@.str.32 = private constant [5 x i8] c"1027\00", align 1
@.str.33 = private constant [14 x i8] c"A.byte_offset\00", align 1
@.str.34 = private constant [11 x i8] c"B.shape[0]\00", align 1
@.str.35 = private constant [5 x i8] c"1024\00", align 1
@.str.36 = private constant [14 x i8] c"B.byte_offset\00", align 1
@.tvm_func.__tvm_set_device = internal unnamed_addr global ptr null, align 8
@.str.37 = private constant [17 x i8] c"__tvm_set_device\00", align 1
@.tvm_func.main_kernel = internal unnamed_addr global ptr null, align 8
@.str.38 = private constant [12 x i8] c"main_kernel\00", align 1
@llvm.global_ctors = appending global [0 x { i32, ptr, ptr }] zeroinitializer

define dllexport i32 @__tvm_ffi_main(ptr nocapture readnone %self_handle, ptr readonly %args, i32 %num_args, ptr nocapture readnone %result) local_unnamed_addr #0 !dbg !5 {
entry:
  %0 = alloca ptr, align 8, !dbg !15
    #dbg_value(ptr %self_handle, !11, !DIExpression(), !26)
    #dbg_value(ptr %args, !12, !DIExpression(), !26)
    #dbg_value(i32 %num_args, !13, !DIExpression(), !26)
    #dbg_value(ptr %result, !14, !DIExpression(), !26)
  %1 = alloca ptr, align 8, !dbg !26
  %stack_ffi_any50 = alloca [5 x %0], align 8, !dbg !26
    #dbg_declare(ptr %stack_ffi_any50, !27, !DIExpression(), !26)
    #dbg_declare(ptr %stack_ffi_any50, !27, !DIExpression(), !26)
  %2 = icmp eq i32 %num_args, 2, !dbg !26
  br i1 %2, label %assert_end, label %assert_fail, !dbg !26, !prof !28

common.ret:                                       ; preds = %main_compute_.exit, %handle_init_end, %handle_init, %assert_fail41, %assert_fail39, %assert_fail37, %assert_fail35, %assert_fail33, %assert_fail31, %assert_fail29, %assert_fail25, %assert_fail23, %assert_fail21, %assert_fail19, %assert_fail17, %assert_fail15, %assert_fail13, %assert_fail11, %assert_fail9, %assert_fail7, %assert_fail5, %assert_fail3, %assert_fail1, %assert_fail
  %common.ret.op = phi i32 [ -1, %assert_fail ], [ -1, %assert_fail1 ], [ -1, %assert_fail3 ], [ -1, %assert_fail5 ], [ -1, %assert_fail7 ], [ -1, %assert_fail9 ], [ -1, %assert_fail11 ], [ -1, %assert_fail13 ], [ -1, %assert_fail15 ], [ -1, %assert_fail17 ], [ -1, %assert_fail19 ], [ -1, %assert_fail21 ], [ -1, %assert_fail23 ], [ -1, %assert_fail25 ], [ -1, %assert_fail29 ], [ -1, %assert_fail31 ], [ -1, %assert_fail33 ], [ -1, %assert_fail35 ], [ -1, %assert_fail37 ], [ -1, %assert_fail39 ], [ -1, %assert_fail41 ], [ %85, %handle_init ], [ %88, %handle_init_end ], [ %common.ret.op.i, %main_compute_.exit ]
  ret i32 %common.ret.op, !dbg !26

assert_fail:                                      ; preds = %entry
  tail call fastcc void @__tvm_set_raised_6(ptr nonnull @.str, i32 6, ptr nonnull @.str.1, ptr nonnull @.str.2, ptr nonnull @.str.3, ptr nonnull @.str.4, ptr nonnull @.str.5, ptr nonnull @.str.6), !dbg !26
  br label %common.ret, !dbg !26

assert_end:                                       ; preds = %entry
  %.not = icmp eq ptr %args, null, !dbg !26
  br i1 %.not, label %assert_fail1, label %assert_end2, !dbg !26, !prof !29

assert_fail1:                                     ; preds = %assert_end
  tail call fastcc void @__tvm_set_raised_6(ptr nonnull @.str, i32 4, ptr nonnull @.str.7, ptr nonnull @.str.4, ptr nonnull @.str.5, ptr nonnull @.str.6, ptr null, ptr null), !dbg !26
  br label %common.ret, !dbg !26

assert_end2:                                      ; preds = %assert_end
  %A_handle.type_index = load i32, ptr %args, align 4, !dbg !26
    #dbg_value(i32 %A_handle.type_index, !30, !DIExpression(), !26)
    #dbg_value(i32 %A_handle.type_index, !30, !DIExpression(), !26)
  %A_handle.type_index.fr = freeze i32 %A_handle.type_index, !dbg !26
  %3 = icmp sgt i32 %A_handle.type_index.fr, 63, !dbg !26
  br i1 %3, label %assert_end4, label %switch.early.test, !dbg !26

switch.early.test:                                ; preds = %assert_end2
  switch i32 %A_handle.type_index.fr, label %assert_fail3 [
    i32 7, label %assert_end4
    i32 4, label %assert_end4
    i32 0, label %assert_end4
  ], !dbg !26

assert_fail3:                                     ; preds = %switch.early.test
  tail call fastcc void @__tvm_set_raised_6(ptr nonnull @.str, i32 6, ptr nonnull @.str.8, ptr nonnull @.str.9, ptr nonnull @.str.4, ptr nonnull @.str.5, ptr nonnull @.str.10, ptr nonnull @.str.11), !dbg !26
  br label %common.ret, !dbg !26

assert_end4:                                      ; preds = %switch.early.test, %switch.early.test, %switch.early.test, %assert_end2
  %4 = getelementptr inbounds i8, ptr %args, i64 8, !dbg !26
  %5 = load ptr, ptr %4, align 8, !dbg !26
  %6 = icmp eq i32 %A_handle.type_index.fr, 70, !dbg !26
  %A_handle.idx = select i1 %6, i64 24, i64 0, !dbg !26
  %A_handle = getelementptr inbounds i8, ptr %5, i64 %A_handle.idx, !dbg !26
    #dbg_declare(ptr %A_handle, !31, !DIExpression(), !26)
    #dbg_declare(ptr %A_handle, !31, !DIExpression(), !26)
  %7 = getelementptr inbounds i8, ptr %args, i64 16, !dbg !26
  %B_handle.type_index = load i32, ptr %7, align 4, !dbg !26
    #dbg_value(i32 %B_handle.type_index, !32, !DIExpression(), !26)
    #dbg_value(i32 %B_handle.type_index, !32, !DIExpression(), !26)
  %B_handle.type_index.fr = freeze i32 %B_handle.type_index, !dbg !26
  %8 = icmp sgt i32 %B_handle.type_index.fr, 63, !dbg !26
  br i1 %8, label %assert_end6, label %switch.early.test47, !dbg !26

switch.early.test47:                              ; preds = %assert_end4
  switch i32 %B_handle.type_index.fr, label %assert_fail5 [
    i32 7, label %assert_end6
    i32 4, label %assert_end6
    i32 0, label %assert_end6
  ], !dbg !26

assert_fail5:                                     ; preds = %switch.early.test47
  tail call fastcc void @__tvm_set_raised_6(ptr nonnull @.str, i32 6, ptr nonnull @.str.8, ptr nonnull @.str.12, ptr nonnull @.str.4, ptr nonnull @.str.5, ptr nonnull @.str.10, ptr nonnull @.str.11), !dbg !26
  br label %common.ret, !dbg !26

assert_end6:                                      ; preds = %switch.early.test47, %switch.early.test47, %switch.early.test47, %assert_end4
  %9 = getelementptr inbounds i8, ptr %args, i64 24, !dbg !26
  %10 = load ptr, ptr %9, align 8, !dbg !26
  %11 = icmp eq i32 %B_handle.type_index.fr, 70, !dbg !26
  %B_handle.idx = select i1 %11, i64 24, i64 0, !dbg !26
  %B_handle = getelementptr inbounds i8, ptr %10, i64 %B_handle.idx, !dbg !26
    #dbg_declare(ptr %B_handle, !33, !DIExpression(), !26)
    #dbg_declare(ptr %B_handle, !33, !DIExpression(), !26)
  %.not51 = icmp eq ptr %5, null, !dbg !26
  br i1 %.not51, label %assert_fail7, label %assert_end8, !dbg !26, !prof !29

assert_fail7:                                     ; preds = %assert_end6
  tail call fastcc void @__tvm_set_raised_6(ptr nonnull @.str, i32 6, ptr nonnull @.str.8, ptr nonnull @.str.9, ptr nonnull @.str.4, ptr nonnull @.str.5, ptr nonnull @.str.10, ptr nonnull @.str.11), !dbg !26
  br label %common.ret, !dbg !26

assert_end8:                                      ; preds = %assert_end6
  %12 = getelementptr inbounds i8, ptr %A_handle, i64 16, !dbg !26
  %13 = load i32, ptr %12, align 4, !dbg !26
  %14 = icmp eq i32 %13, 1, !dbg !26
  br i1 %14, label %assert_end10, label %assert_fail9, !dbg !26, !prof !28

assert_fail9:                                     ; preds = %assert_end8
  tail call fastcc void @__tvm_set_raised_12(ptr nonnull @.str.13, i32 8, ptr nonnull @.str.14, ptr nonnull @.str.15, ptr nonnull @.str.16, ptr nonnull @.str.9, ptr nonnull @.str.10, ptr nonnull @.str.12), !dbg !26
  br label %common.ret, !dbg !26

assert_end10:                                     ; preds = %assert_end8
  %15 = getelementptr inbounds i8, ptr %A_handle, i64 22, !dbg !26
  %16 = load i16, ptr %15, align 2, !dbg !26
  %17 = icmp eq i16 %16, 1, !dbg !26
  %18 = getelementptr inbounds i8, ptr %A_handle, i64 21, !dbg !26
  %19 = load i8, ptr %18, align 1, !dbg !26
  %20 = icmp eq i8 %19, 32, !dbg !26
  %21 = getelementptr inbounds i8, ptr %A_handle, i64 20, !dbg !26
  %22 = load i8, ptr %21, align 1, !dbg !26
  %23 = icmp eq i8 %22, 2, !dbg !26
  %24 = and i1 %20, %23, !dbg !26
  %25 = and i1 %17, %24, !dbg !26
  br i1 %25, label %assert_end12, label %assert_fail11, !dbg !26, !prof !28

assert_fail11:                                    ; preds = %assert_end10
  tail call fastcc void @__tvm_set_raised_12(ptr nonnull @.str, i32 8, ptr nonnull @.str.14, ptr nonnull @.str.15, ptr nonnull @.str.17, ptr nonnull @.str.9, ptr nonnull @.str.10, ptr nonnull @.str.18), !dbg !26
  br label %common.ret, !dbg !26

assert_end12:                                     ; preds = %assert_end10
  %26 = getelementptr inbounds i8, ptr %A_handle, i64 24, !dbg !26
  %main.A_handle_shape = load ptr, ptr %26, align 8, !dbg !26
    #dbg_declare(ptr %main.A_handle_shape, !34, !DIExpression(), !26)
    #dbg_declare(ptr %main.A_handle_shape, !34, !DIExpression(), !26)
  %27 = getelementptr inbounds i8, ptr %A_handle, i64 32, !dbg !26
  %main.A_handle_strides = load ptr, ptr %27, align 8, !dbg !26
    #dbg_declare(ptr %main.A_handle_strides, !35, !DIExpression(), !26)
    #dbg_declare(ptr %main.A_handle_strides, !35, !DIExpression(), !26)
  %28 = getelementptr inbounds i8, ptr %A_handle, i64 8, !dbg !26
  %29 = load i32, ptr %28, align 4, !dbg !26
  %30 = icmp eq i32 %29, 8, !dbg !26
  br i1 %30, label %assert_end14, label %assert_fail13, !dbg !26, !prof !28

assert_fail13:                                    ; preds = %assert_end12
  tail call fastcc void @__tvm_set_raised_12(ptr nonnull @.str.13, i32 8, ptr nonnull @.str.14, ptr nonnull @.str.15, ptr nonnull @.str.19, ptr nonnull @.str.9, ptr nonnull @.str.10, ptr nonnull @.str.20), !dbg !26
  br label %common.ret, !dbg !26

assert_end14:                                     ; preds = %assert_end12
  %31 = getelementptr inbounds i8, ptr %A_handle, i64 12, !dbg !26
  %dev_id = load i32, ptr %31, align 4, !dbg !26
    #dbg_value(i32 %dev_id, !36, !DIExpression(), !26)
    #dbg_value(i32 %dev_id, !36, !DIExpression(), !26)
  %A = load ptr, ptr %A_handle, align 8, !dbg !26
    #dbg_declare(ptr %A, !37, !DIExpression(), !26)
    #dbg_declare(ptr %A, !37, !DIExpression(), !26)
  call void @llvm.assume(i1 true) [ "align"(ptr %A, i64 64) ], !dbg !26
  %.not52 = icmp eq ptr %10, null, !dbg !26
  br i1 %.not52, label %assert_fail15, label %assert_end16, !dbg !26, !prof !29

assert_fail15:                                    ; preds = %assert_end14
  tail call fastcc void @__tvm_set_raised_6(ptr nonnull @.str, i32 6, ptr nonnull @.str.8, ptr nonnull @.str.12, ptr nonnull @.str.4, ptr nonnull @.str.5, ptr nonnull @.str.10, ptr nonnull @.str.11), !dbg !26
  br label %common.ret, !dbg !26

assert_end16:                                     ; preds = %assert_end14
  %32 = getelementptr inbounds i8, ptr %B_handle, i64 16, !dbg !26
  %33 = load i32, ptr %32, align 4, !dbg !26
  %34 = icmp eq i32 %33, 1, !dbg !26
  br i1 %34, label %assert_end18, label %assert_fail17, !dbg !26, !prof !28

assert_fail17:                                    ; preds = %assert_end16
  tail call fastcc void @__tvm_set_raised_12(ptr nonnull @.str.13, i32 8, ptr nonnull @.str.14, ptr nonnull @.str.21, ptr nonnull @.str.16, ptr nonnull @.str.12, ptr nonnull @.str.10, ptr nonnull @.str.12), !dbg !26
  br label %common.ret, !dbg !26

assert_end18:                                     ; preds = %assert_end16
  %35 = getelementptr inbounds i8, ptr %B_handle, i64 22, !dbg !26
  %36 = load i16, ptr %35, align 2, !dbg !26
  %37 = icmp eq i16 %36, 1, !dbg !26
  %38 = getelementptr inbounds i8, ptr %B_handle, i64 21, !dbg !26
  %39 = load i8, ptr %38, align 1, !dbg !26
  %40 = icmp eq i8 %39, 32, !dbg !26
  %41 = getelementptr inbounds i8, ptr %B_handle, i64 20, !dbg !26
  %42 = load i8, ptr %41, align 1, !dbg !26
  %43 = icmp eq i8 %42, 2, !dbg !26
  %44 = and i1 %40, %43, !dbg !26
  %45 = and i1 %37, %44, !dbg !26
  br i1 %45, label %assert_end20, label %assert_fail19, !dbg !26, !prof !28

assert_fail19:                                    ; preds = %assert_end18
  tail call fastcc void @__tvm_set_raised_12(ptr nonnull @.str, i32 8, ptr nonnull @.str.14, ptr nonnull @.str.21, ptr nonnull @.str.17, ptr nonnull @.str.12, ptr nonnull @.str.10, ptr nonnull @.str.18), !dbg !26
  br label %common.ret, !dbg !26

assert_end20:                                     ; preds = %assert_end18
  %46 = getelementptr inbounds i8, ptr %B_handle, i64 24, !dbg !26
  %main.B_handle_shape = load ptr, ptr %46, align 8, !dbg !26
    #dbg_declare(ptr %main.B_handle_shape, !38, !DIExpression(), !26)
    #dbg_declare(ptr %main.B_handle_shape, !38, !DIExpression(), !26)
  %47 = getelementptr inbounds i8, ptr %B_handle, i64 32, !dbg !26
  %main.B_handle_strides = load ptr, ptr %47, align 8, !dbg !26
    #dbg_declare(ptr %main.B_handle_strides, !39, !DIExpression(), !26)
    #dbg_declare(ptr %main.B_handle_strides, !39, !DIExpression(), !26)
  %48 = getelementptr inbounds i8, ptr %B_handle, i64 8, !dbg !26
  %49 = load i32, ptr %48, align 4, !dbg !26
  %50 = icmp eq i32 %49, 8, !dbg !26
  br i1 %50, label %assert_end22, label %assert_fail21, !dbg !26, !prof !28

assert_fail21:                                    ; preds = %assert_end20
  tail call fastcc void @__tvm_set_raised_12(ptr nonnull @.str.13, i32 8, ptr nonnull @.str.14, ptr nonnull @.str.21, ptr nonnull @.str.19, ptr nonnull @.str.12, ptr nonnull @.str.10, ptr nonnull @.str.20), !dbg !26
  br label %common.ret, !dbg !26

assert_end22:                                     ; preds = %assert_end20
  %B = load ptr, ptr %B_handle, align 8, !dbg !26
    #dbg_declare(ptr %B, !40, !DIExpression(), !26)
    #dbg_declare(ptr %B, !40, !DIExpression(), !26)
  call void @llvm.assume(i1 true) [ "align"(ptr %B, i64 64) ], !dbg !26
  %.not53 = icmp eq ptr %main.A_handle_strides, null, !dbg !26
  br i1 %.not53, label %if_end, label %if_then, !dbg !26, !prof !29

if_then:                                          ; preds = %assert_end22
  %51 = load i64, ptr %main.A_handle_strides, align 8, !dbg !26
  %52 = and i64 %51, 4294967295, !dbg !26
  %53 = icmp eq i64 %52, 1, !dbg !26
  br i1 %53, label %if_end, label %assert_fail23, !dbg !26, !prof !28

if_end:                                           ; preds = %if_then, %assert_end22
  %.not54 = icmp eq ptr %A, null, !dbg !26
  br i1 %.not54, label %assert_fail25, label %assert_end26, !dbg !26, !prof !29

assert_fail23:                                    ; preds = %if_then
  tail call fastcc void @__tvm_set_raised_12(ptr nonnull @.str.13, i32 7, ptr nonnull @.str.14, ptr nonnull @.str.15, ptr nonnull @.str.22, ptr nonnull @.str.9, ptr nonnull @.str.23, ptr null), !dbg !26
  br label %common.ret, !dbg !26

assert_fail25:                                    ; preds = %if_end
  tail call fastcc void @__tvm_set_raised_6(ptr nonnull @.str.13, i32 6, ptr nonnull @.str.15, ptr nonnull @.str.24, ptr nonnull @.str.9, ptr nonnull @.str.4, ptr nonnull @.str.5, ptr nonnull @.str.25), !dbg !26
  br label %common.ret, !dbg !26

assert_end26:                                     ; preds = %if_end
  %.not55 = icmp eq ptr %main.B_handle_strides, null, !dbg !26
  br i1 %.not55, label %if_end28, label %if_then27, !dbg !26, !prof !29

if_then27:                                        ; preds = %assert_end26
  %54 = load i64, ptr %main.B_handle_strides, align 8, !dbg !26
  %55 = and i64 %54, 4294967295, !dbg !26
  %56 = icmp eq i64 %55, 1, !dbg !26
  br i1 %56, label %if_end28, label %assert_fail29, !dbg !26, !prof !28

if_end28:                                         ; preds = %if_then27, %assert_end26
  %57 = getelementptr inbounds i8, ptr %B_handle, i64 12, !dbg !26
  %58 = load i32, ptr %57, align 4, !dbg !26
  %59 = icmp eq i32 %dev_id, %58, !dbg !26
  br i1 %59, label %assert_end32, label %assert_fail31, !dbg !26, !prof !28

assert_fail29:                                    ; preds = %if_then27
  tail call fastcc void @__tvm_set_raised_12(ptr nonnull @.str.13, i32 7, ptr nonnull @.str.14, ptr nonnull @.str.21, ptr nonnull @.str.22, ptr nonnull @.str.12, ptr nonnull @.str.23, ptr null), !dbg !26
  br label %common.ret, !dbg !26

assert_fail31:                                    ; preds = %if_end28
  tail call fastcc void @__tvm_set_raised_12(ptr nonnull @.str.13, i32 8, ptr nonnull @.str.14, ptr nonnull @.str.26, ptr nonnull @.str.27, ptr nonnull @.str.12, ptr nonnull @.str.28, ptr nonnull @.str.29), !dbg !26
  br label %common.ret, !dbg !26

assert_end32:                                     ; preds = %if_end28
  %.not56 = icmp eq ptr %B, null, !dbg !26
  br i1 %.not56, label %assert_fail33, label %assert_end34, !dbg !26, !prof !29

assert_fail33:                                    ; preds = %assert_end32
  tail call fastcc void @__tvm_set_raised_6(ptr nonnull @.str.13, i32 6, ptr nonnull @.str.21, ptr nonnull @.str.24, ptr nonnull @.str.12, ptr nonnull @.str.4, ptr nonnull @.str.5, ptr nonnull @.str.25), !dbg !26
  br label %common.ret, !dbg !26

assert_end34:                                     ; preds = %assert_end32
  %60 = load i64, ptr %main.A_handle_shape, align 8, !dbg !26
  %61 = and i64 %60, 4294967295, !dbg !26
  %62 = icmp eq i64 %61, 1027, !dbg !26
  br i1 %62, label %assert_end36, label %assert_fail35, !dbg !26, !prof !28

assert_fail35:                                    ; preds = %assert_end34

[21:08:23] /workspace/tvm/src/target/opt/build_metal_off.cc:32: Warning: Metal runtime not enabled, return a source module...

### Matrix Multiplication

In [39]:
@tvm.script.ir_module
class MyModuleMatmul:
    @T.prim_func
    def main(
        A: T.Buffer((1024, 1024), "float32"),
        B: T.Buffer((1024, 1024), "float32"),
        C: T.Buffer((1024, 1024), "float32"),
    ) -> None:
        T.func_attr({"global_symbol": "main", "tirx.noalias": True})
        for i, j, k in T.grid(1024, 1024, 1024):
            with T.sblock("C"):
                vi, vj, vk = T.axis.remap("SSR", [i, j, k])
                with T.init():
                    C[vi, vj] = 0.0
                C[vi, vj] = C[vi, vj] + A[vi, vk] * B[vk, vj]

In [40]:
def blocking(sch, tile_local_y, tile_local_x, tile_block_y, tile_block_x, tile_k):
    block_C = sch.get_sblock("C")
    C_local = sch.cache_write(block_C, 0, "local")

    i, j, k = sch.get_loops(block=block_C)

    i0, i1, i2 = sch.split(loop=i, factors=[None, tile_block_y, tile_local_y])
    j0, j1, j2 = sch.split(loop=j, factors=[None, tile_block_x, tile_local_x])
    k0, k1 = sch.split(loop=k, factors=[None, tile_k])
    sch.unroll(k1)
    sch.reorder(i0, j0, i1, j1, k0, k1, i2, j2)
    sch.reverse_compute_at(C_local, j1)

    sch.bind(i0, "blockIdx.y")
    sch.bind(j0, "blockIdx.x")

    sch.bind(i1, "threadIdx.y")
    sch.bind(j1, "threadIdx.x")
    sch.decompose_reduction(block_C, k0)

    return sch


sch = tvm.s_tir.Schedule(MyModuleMatmul)
sch = blocking(sch, 8, 8, 8, 8, 4)
sch.mod.show()

In [42]:
rt_mod = tvm.compile(sch.mod, target="cuda")
dev = tvm.cuda(0)
A_np = np.random.uniform(size=(1024, 1024)).astype("float32")
B_np = np.random.uniform(size=(1024, 1024)).astype("float32")
A_nd = tvm.runtime.tensor(A_np, device=tvm.cuda(0))
B_nd = tvm.runtime.tensor(B_np, device=tvm.cuda(0))
C_nd = tvm.runtime.tensor(np.zeros((1024, 1024), dtype="float32"), device=tvm.cuda(0))

num_flop = 2 * 1024 * 1024 * 1024
evaluator = rt_mod.mod.time_evaluator("main", dev, number=10)

print("GEMM-Blocking: %f GFLOPS" % (num_flop / evaluator(A_nd, B_nd, C_nd).mean / 1e9))

GEMM-Blocking: 138.021014 GFLOPS

In [43]:
def cache_read_and_coop_fetch(sch, block, nthread, read_idx, read_loc):
    read_cache = sch.cache_read(
        block=block, read_buffer_index=read_idx, storage_scope="shared"
    )
    sch.compute_at(block=read_cache, loop=read_loc)
    # vectorized cooperative fetch
    inner0, inner1 = sch.get_loops(block=read_cache)[-2:]
    inner = sch.fuse(inner0, inner1)
    _, tx, vec = sch.split(loop=inner, factors=[None, nthread, 4])
    sch.vectorize(vec)
    sch.bind(tx, "threadIdx.x")


def blocking_with_shared(
    sch, tile_local_y, tile_local_x, tile_block_y, tile_block_x, tile_k
):
    block_C = sch.get_sblock("C")
    C_local = sch.cache_write(block_C, 0, "local")

    i, j, k = sch.get_loops(block=block_C)

    i0, i1, i2 = sch.split(loop=i, factors=[None, tile_block_y, tile_local_y])
    j0, j1, j2 = sch.split(loop=j, factors=[None, tile_block_x, tile_local_x])
    k0, k1 = sch.split(loop=k, factors=[None, tile_k])

    sch.reorder(i0, j0, i1, j1, k0, k1, i2, j2)
    sch.reverse_compute_at(C_local, j1)

    sch.bind(i0, "blockIdx.y")
    sch.bind(j0, "blockIdx.x")

    tx = sch.fuse(i1, j1)
    sch.bind(tx, "threadIdx.x")
    nthread = tile_block_y * tile_block_x
    cache_read_and_coop_fetch(sch, block_C, nthread, 0, k0)
    cache_read_and_coop_fetch(sch, block_C, nthread, 1, k0)
    sch.decompose_reduction(block_C, k0)

    return sch


sch = tvm.s_tir.Schedule(MyModuleMatmul)
sch = blocking_with_shared(sch, 8, 8, 8, 8, 8)
sch.mod.show()

In [44]:
rt_mod = tvm.compile(sch.mod, target="cuda")
dev = tvm.cuda(0)
evaluator = rt_mod.mod.time_evaluator("main", dev, number=10)

print("GEMM-Blocking: %f GFLOPS" % (num_flop / evaluator(A_nd, B_nd, C_nd).mean / 1e9))

GEMM-Blocking: 245.134181 GFLOPS

In [45]:
from tvm.s_tir import meta_schedule as ms

database = ms.tune_tir(
    mod=MyModuleMatmul,
    target="nvidia/tesla-p100",
    max_trials_global=64,
    num_trials_per_iter=64,
    work_dir="./tune_tmp",
)
sch = ms.tir_integration.compile_tir(database, MyModuleMatmul, "nvidia/tesla-p100")
sch.mod.show()

2026-04-18 21:26:47 [INFO] Logging directory: ./tune_tmp/logs
2026-04-18 21:27:10 [INFO] LocalBuilder: max_workers = 8

[21:27:16] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m1` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:16] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m1` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:16] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m2` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:16] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m2` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:16] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m1` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:16] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m1` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`

2026-04-18 21:27:17 [INFO] LocalRunner: max_workers = 1
2026-04-18 21:27:20 [INFO] [task_scheduler.cc:171] Initializing Task #0: "main"

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,main,2147483648,1,N/A,N/A,N/A,0,

2026-04-18 21:27:20 [DEBUG] [task_scheduler.cc:330]
 ID | Name |       FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
---------------------------------------------------------------------------------------------------------
  0 | main | 2147483648 |      1 |            N/A |          N/A |                   N/A |      0 |
---------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0


Total trials: 0
Total latency (us): 0

2026-04-18 21:27:20 [INFO] [task_scheduler.cc:192] TaskScheduler picks Task #0: "main"
2026-04-18 21:27:24 [INFO] [task_scheduler.cc:205] Sending 63 sample(s) to builder

[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m1` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m1` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m1` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m1` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m1` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m2` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m2` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m1` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m2` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m2` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m1` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m2` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m1` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m1` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m2` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m1` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m1` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m1` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m1` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m2` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m1` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m1` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m2` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m2` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m1` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m2` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m1` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`

[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m1` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m1` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m1` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m1` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m1` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m2` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m2` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m1` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m1` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m1` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m1` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m2` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m2` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m1` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:29] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m1` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:30] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m1` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:30] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m1` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:30] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m2` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:30] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m2` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:30] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m1` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:27:30] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m1` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`

2026-04-18 21:28:01 [INFO] [task_scheduler.cc:207] Sending 63 sample(s) to runner
2026-04-18 21:28:01 [INFO] [task_scheduler.cc:249] [Updated] Task #0: "main"

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,main,2147483648,1,N/A,N/A,N/A,63,

2026-04-18 21:28:01 [DEBUG] [task_scheduler.cc:330]
 ID | Name |       FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
---------------------------------------------------------------------------------------------------------
  0 | main | 2147483648 |      1 |            N/A |          N/A |                   N/A |     63 |
---------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0


Total trials: 0
Total latency (us): 0

2026-04-18 21:28:01 [INFO] [task_scheduler.cc:192] TaskScheduler picks Task #0: "main"
2026-04-18 21:28:06 [INFO] [task_scheduler.cc:205] Sending 1 sample(s) to builder

[21:28:10] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m1` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:28:10] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m1` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:28:10] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m2` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:28:10] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m2` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:28:10] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m1` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
[21:28:10] /workspace/tvm/src/target/llvm/llvm_instance.cc:219: Error: Using LLVM 19.1.7 with `-mcpu=apple-m1` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`

2026-04-18 21:28:40 [INFO] [task_scheduler.cc:207] Sending 1 sample(s) to runner
2026-04-18 21:28:40 [INFO] [task_scheduler.cc:249] [Updated] Task #0: "main"

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,main,2147483648,1,N/A,N/A,N/A,64,

Total trials: 0
Total latency (us): 0

2026-04-18 21:28:40 [DEBUG] [task_scheduler.cc:330]
 ID | Name |       FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
---------------------------------------------------------------------------------------------------------
  0 | main | 2147483648 |      1 |            N/A |          N/A |                   N/A |     64 |
---------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0

2026-04-18 21:28:40 [INFO] [task_scheduler.cc:272] Task #0 has finished. Remaining task(s): 0

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,main,2147483648,1,N/A,N/A,N/A,64,Y

2026-04-18 21:28:40 [DEBUG] [task_scheduler.cc:330]
 ID | Name |       FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
---------------------------------------------------------------------------------------------------------
  0 | main | 2147483648 |      1 |            N/A |          N/A |                   N/A |     64 |    Y
---------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0


Total trials: 0
Total latency (us): 0

AttributeError: 'NoneType' object has no attribute 'mod'

In [ ]:
rt_mod = tvm.compile(sch.mod, target="nvidia/tesla-p100")
dev = tvm.cuda(0)
evaluator = rt_mod.mod.time_evaluator("main", dev, number=10)

print("MetaSchedule: %f GFLOPS" % (num_flop / evaluator(A_nd, B_nd, C_nd).mean / 1e9))